### ISSUE TITLE
console spam message,

### ISSUE THREAD

**Issue by chaixshot** [warxander/vSql#3]
SCRIPT ERROR in tick: System.NullReferenceException: Object reference not set to an instance of an object.

SCRIPT ERROR in tick: System.NullReferenceException: Object reference not set to an instance of an object.

SCRIPT ERROR in tick: System.NullReferenceException: Object reference not set to an instance of an object.

SCRIPT ERROR in tick: System.NullReferenceException: Object reference not set to an instance of an object.

SCRIPT ERROR in tick: System.NullReferenceException: Object reference not set to an instance of an object.

SCRIPT ERROR in tick: System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by warxander** [comment]
Make sure you did everything from `How to Install` section.

**Comment by chaixshot** [comment]
mysql work already. But this problem found sometimes when the server starts on function
`MySQL.ready(function()  end)`

**Comment by chaixshot** [comment]
[mysql-async.zip](https://github.com/warxander/vSql/files/3800286/mysql-async.zip)
mysql-async modified for vSQL.

**Comment by chaixshot** [comment]
`SCRIPT ERROR in tick: System.NullReferenceException: Object reference not set to an instance of an object.`

spam in console infinity.

**Comment by chaixshot** [comment]
Maybe can add exports is_ready for vSql?

```
function MySQL.ready (callback)
    Citizen.CreateThread(function ()
        while GetResourceState('vSql') ~= 'started' do
            Citizen.Wait(100)
        end
	while not exports['vSql']:is_ready() do
		Citizen.Wait(0)
	end
        callback()
    end)
end
```

**Comment by chaixshot** [comment]
![image](https://user-images.githubusercontent.com/13221018/68072511-36b32d00-fdb9-11e9-9c18-cb6d11bd2ca3.png)
exports.vSql:ready() error

**Comment by warxander** [comment]
Added in latest version, check `Releases`.

**Comment by warxander** [comment]
Don't try to use both `mysql-async` and `vSql`.
