### ISSUE TITLE
Less cpu load.

### ISSUE THREAD

**Issue by chaixshot** [warxander/vSql#6]
Sometimes have many sql query on one time, this make cpu over 20% on 100+ players , players get high ping and timeout 60 sec.

Maybe you can make Query queue for sql, I don't know c# but i know you can do it.

This my idea on lua.
```
local sqlqueue = 0
while sqlqueue > 5 do
	Citizen.Wait(0)
end
local res = 0
local finishedQuery = false
exports['vSql']:execute_async(safeQuery(query), safeParameters(params), function (result)
	res = result
	finishedQuery = true
end)
repeat Citizen.Wait(0) until finishedQuery == true
sqlqueue = sqlqueue-1
return res
```

**Comment by warxander** [comment]
It makes no sense, as vSql is already working in async mode.
I suggest, you're using ESX + tons of related resources.
Most of them have awful quality and poor performance.
Try to fix or get rid of them.
