### ISSUE TITLE
esx_addonaccount/server/main.lua:9 error

### ISSUE THREAD

**Issue by JaNL4U** [warxander/vSql#9]
When changing the trigger from mysql to vSQL this happends 

SCRIPT ERROR: @esx_addonaccount/server/main.lua:9: attempt to get length of a nil value (local 'result')
> void vSql.VSql+<>c__DisplayClass4_0.<.ctor>b__5(?)+() => { } (@vSql/vSql.net.dll:0)
> Task vSql.VSql.OnTick() (@vSql/vSql.net.dll:0)

vSql.ready(function()
	local result = vSql.Async.fetchAll('SELECT * FROM addon_account')

	for i=1, #result, 1 do
		local name   = result[i].name
		local label  = result[i].label
		local shared = result[i].shared

		local result2 = vSql.Async.fetchAll('SELECT * FROM addon_account_data WHERE account_name = @account_name', {
			['@account_name'] = name
		})

		if shared == 0 then
			table.insert(AccountsIndex, name)
			Accounts[name] = {}

			for j=1, #result2, 1 do
				local addonAccount = CreateAddonAccount(name, result2[j].owner, result2[j].money)
				table.insert(Accounts[name], addonAccount)
			end
		else
			local money = nil

			if #result2 == 0 then
				vSql.Async.execute('INSERT INTO addon_account_data (account_name, money, owner) VALUES (@account_name, @money, NULL)', {
					['@account_name'] = name,
					['@money']        = 0
				})

				money = 0
			else
				money = result2[1].money
			end

			local addonAccount   = CreateAddonAccount(name, nil, money)
			SharedAccounts[name] = addonAccount
		end
	end
end)

**Comment by warxander** [comment]
`local result = vSql.Async.fetchAll`

It's not sync function call, you should use callbacks for processing result when it will be ready.

`vSql.Async.fetchAll('SELECT * FROM addon_account', function(result)
end)`
